// JS Object for team members
const lists = [
  {
    Heads: "Vice-President",
    Name: "Sahil Soujani",
    Email: "sahil.22010595@viit.ac.in",
    Contact_no: "9822713136",
    Year: "TY",
    Division: "B",
    Insta_ID: "soujanisahil",
    LinkedIn: "https://www.linkedin.com/in/soujanisahil",
    image: "images/img1.webp",
  },
  {
    Heads: "Secretary",
    Name: "Pranav Bagade",
    Email: "pranav.22010496@viit.ac.in",
    Contact_no: "9405298380",
    Year: "TY",
    Division: "A",
    Insta_ID: "vedant",
    LinkedIn: "https://in.linkedin.com/in/pranav-bagade",
    image: "",
  },
  {
    Heads: "Treasurer",
    Name: "Nayan Chandak",
    Email: "nayan.22010343@viit.ac.in",
    Contact_no: "9028508288",
    Year: "TY",
    Division: "A",
    Insta_ID: "nayanchandak ",
    image: "images/img1.webp",
  },
  {
    Heads: "Human Resource Manager",
    Name: "Rahul Choubey",
    Email: "rahul.22011024@viit.ac.in",
    Contact_no: "7588981976",
    Year: "TY",
    Division: "B",
    Insta_ID: "__rahul_choubey",
    LinkedIn: "https://www.linkedin.com/in/choubeyrahul",
    image: "",
  },
  {
    Heads: "Publicity",
    Name: "Shruti Jadhav",
    Email: "shruti.22120119@viit.ac.in ",
    Contact_no: "7030057089",
    Year: "TY",
    Division: "A",
    Insta_ID: "shrutijadhav.23 ",
    LinkedIn: "https://www.linkedin.com/in/shruti-jadhav-744650208/",
    image: "images/img1.webp",
  },
  {
    Heads: "Event Management",
    Name: "Atharva Jadhav",
    Email: "atharva.22010121@viit.ac.in",
    Contact_no: "7020679825",
    Year: "TY",
    Division: "A",
    Insta_ID: "atharva2436",
    image: "images/img1.webp",
  },
  {
    Heads: "Techinal Activity Incharge",
    Name: "Neemeesh Khanzode",
    Email: "neemeesh.22010929@viit.ac.in",
    Contact_no: "9423612064",
    Year: "TY",
    Division: "B",
    Insta_ID: "neemeesh_khanzode",
    LinkedIn: "https://www.linkedin.com/in/neemeesh-khanzode/",
    image: "images/img1.webp",
  },
  {
    Heads: "Video Creator",
    Name: "Shardul Khandebharad",
    Email: "shardul.22010207@viit.ac.in",
    Contact_no: "9829704334",
    Year: "TY",
    Division: "B",
    Insta_ID: "shardul.a.k_2002",
    LinkedIn: "https://www.linkedin.com/in/shardulkhandebharad/",
    image: "images/img1.webp",
  },
  {
    Heads: "Content",
    Name: "Aditi Nikam",
    Email: "aditi.22120155@viit.ac.in",
    Contact_no: "7219113545",
    Year: "TY",
    Division: "B",
    Insta_ID: "_aditi_nikam_",
    LinkedIn: "www.linkedin.com/in/aditinikam",
    image: "images/img1.webp",
  },
  {
    Heads: "Documentation & Magazine",
    Name: "Adnan Burhanpurwala",
    Email: "adnan.22010210@viit.ac.in",
    Contact_no: "9004963200",
    Year: "TY",
    Division: "B",
    Insta_ID: "adnan_b07_",
    LinkedIn: "https://www.linkedin.com/in/adnan-burhanpurwala-aa2404206/",
    image: "images/img1.webp",
  },
  {
    Heads: "Design",
    Name: "Shreya Patil",
    Email: "shreya.22010789@viit.ac.in",
    Contact_no: "9730836615",
    Year: "TY",
    Division: "B",
    Insta_ID: "_shreya_1402",
    LinkedIn: "https://www.linkedin.com/in/shreya-patil-79b541219",
    image: "images/img1.webp",
  },
  {
    Heads: "Youtube",
    Name: "Shreya Patil",
    Email: "ruchika.22010715@viit.ac.in",
    Contact_no: "8888844659",
    Year: "TY",
    Division: "A",
    Insta_ID: "ruchika_taware",
    LinkedIn: "https://www.linkedin.com/in/ruchika-taware-76463820a/",
    image: "images/img1.webp",
  },
  {
    Heads: "Photography",
    Name: "Prasad Awhale",
    Email: "prasad.22011075@viit.ac.in",
    Contact_no: "9096115387",
    Year: "TY",
    Division: "B",
    Insta_ID: "_prasadawhale",
    LinkedIn: "https://www.linkedin.com/in/prasadawhale",
    image: "images/img1.webp",
  },
];
// exporting lists
export default lists;
